# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d3abc29bf794f41d40af9e0c3b08be4f6a577b678b3b152bcab9ada5d1d26b896e0d0bd54a252bbed99bf3d3fc4a291e8fd6a346c01127f7c7b02a8937cdf7c

test:
  secret_key_base: 3cfe5cd057f183bae8ba10a21b72bc70496f4646ea8d77413991e17b8e10043dcb9b8b1074c1870614ab132a88d4ac9204e58b4bc41b0a944dcec4a4ab356e37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
